


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bib_input = QtWidgets.QLineEdit(self.centralwidget)
        self.bib_input.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bib_input.setFont(font)
        self.bib_input.setAlignment(QtCore.Qt.AlignCenter)
        self.bib_input.setObjectName("bib_input")
        self.gridLayout.addWidget(self.bib_input, 0, 3, 1, 1)
        self.first_timer_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.first_timer_label.setFont(font)
        self.first_timer_label.setText("")
        self.first_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_timer_label.setObjectName("first_timer_label")
        self.gridLayout.addWidget(self.first_timer_label, 1, 3, 1, 1)
        self.second_timer_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.second_timer_label.setFont(font)
        self.second_timer_label.setText("")
        self.second_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_timer_label.setObjectName("second_timer_label")
        self.gridLayout.addWidget(self.second_timer_label, 2, 3, 1, 1)
        self.third_timer_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.third_timer_label.setFont(font)
        self.third_timer_label.setText("")
        self.third_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_timer_label.setObjectName("third_timer_label")
        self.gridLayout.addWidget(self.third_timer_label, 3, 3, 1, 1)
        self.fourth_timer_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.fourth_timer_label.setFont(font)
        self.fourth_timer_label.setText("")
        self.fourth_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fourth_timer_label.setObjectName("fourth_timer_label")
        self.gridLayout.addWidget(self.fourth_timer_label, 4, 3, 1, 1)
        self.race_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.race_list.sizePolicy().hasHeightForWidth())
        self.race_list.setSizePolicy(sizePolicy)
        self.race_list.setMaximumSize(QtCore.QSize(500, 100))
        self.race_list.setObjectName("race_list")
        self.gridLayout.addWidget(self.race_list, 5, 0, 1, 1)
        self.strart_button = QtWidgets.QPushButton(self.centralwidget)
        self.strart_button.setMaximumSize(QtCore.QSize(16777215, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.strart_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.strart_button.setFont(font)
        self.strart_button.setObjectName("strart_button")
        self.gridLayout.addWidget(self.strart_button, 5, 1, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setMaximumSize(QtCore.QSize(16777215, 60))
        self.stop_button.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.stop_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arimo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 5, 2, 1, 1)
        self.finishers_list = QtWidgets.QListWidget(self.centralwidget)
        self.finishers_list.setObjectName("finishers_list")
        self.gridLayout.addWidget(self.finishers_list, 0, 0, 5, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menubar.setObjectName("menubar")
        self.menuLive = QtWidgets.QMenu(self.menubar)
        self.menuLive.setObjectName("menuLive")
        self.menuLive_2 = QtWidgets.QMenu(self.menubar)
        self.menuLive_2.setObjectName("menuLive_2")
        self.menuResults = QtWidgets.QMenu(self.menubar)
        self.menuResults.setObjectName("menuResults")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Race = QtWidgets.QAction(MainWindow)
        self.actionNew_Race.setObjectName("actionNew_Race")
        self.actionContinue_Race = QtWidgets.QAction(MainWindow)
        self.actionContinue_Race.setObjectName("actionContinue_Race")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.menuLive.addAction(self.actionNew_Race)
        self.menuLive.addAction(self.actionContinue_Race)
        self.menuLive.addAction(self.actionClear_All)
        self.menubar.addAction(self.menuLive.menuAction())
        self.menubar.addAction(self.menuLive_2.menuAction())
        self.menubar.addAction(self.menuResults.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TimeKeeper"))
        self.strart_button.setText(_translate("MainWindow", "START"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.menuLive.setTitle(_translate("MainWindow", "File"))
        self.menuLive_2.setTitle(_translate("MainWindow", "Live"))
        self.menuResults.setTitle(_translate("MainWindow", "Results"))
        self.actionNew_Race.setText(_translate("MainWindow", "New Race"))
        self.actionContinue_Race.setText(_translate("MainWindow", "Continue Race"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
